extends Node
## Global audio (autoload "Sfx"): UI/one-shot voices, positional one-shots and loops,
## ambience bed and music with crossfades. Files: art/audio/{sfx,amb,mus,loop}_*.wav
## (generated by tools/gen_audio.py). Missing names are ignored (warned once).

const VOICES := 10

var _sfx: Array[AudioStreamPlayer] = []
var _next := 0
var _amb: AudioStreamPlayer
var _mus: AudioStreamPlayer
var _cache: Dictionary = {}
var _missing: Dictionary = {}


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for bus in ["SFX", "Ambience", "Music"]:
		if AudioServer.get_bus_index(bus) == -1:
			AudioServer.add_bus()
			AudioServer.set_bus_name(AudioServer.bus_count - 1, bus)
	for i in VOICES:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_sfx.append(p)
	_amb = AudioStreamPlayer.new()
	_amb.bus = "Ambience"
	_mus = AudioStreamPlayer.new()
	_mus.bus = "Music"
	add_child(_amb)
	add_child(_mus)
	for bus in ["Master", "SFX", "Ambience", "Music"]:
		var v = Loc.load_setting("vol_" + bus)
		if v != null:
			set_volume(bus, float(v))


func set_volume(bus: String, linear: float) -> void:
	var i := AudioServer.get_bus_index(bus)
	if i >= 0:
		AudioServer.set_bus_volume_db(i, linear_to_db(maxf(linear, 0.0001)))


func get_volume(bus: String) -> float:
	var i := AudioServer.get_bus_index(bus)
	return db_to_linear(AudioServer.get_bus_volume_db(i)) if i >= 0 else 1.0


func stream(name: String, loop := false) -> AudioStreamWAV:
	var key := name + ("#loop" if loop else "")
	if _cache.has(key):
		return _cache[key]
	var path := "res://art/audio/%s.wav" % name
	if not ResourceLoader.exists(path):
		if not _missing.has(name):
			_missing[name] = true
			push_warning("missing sound " + name)
		return null
	var s: AudioStreamWAV = load(path)
	if loop:
		s = s.duplicate()
		s.loop_mode = AudioStreamWAV.LOOP_FORWARD
		s.loop_end = int(s.get_length() * s.mix_rate)
	_cache[key] = s
	return s


func play(name: String, db := 0.0, pitch := 1.0) -> void:
	var s := stream("sfx_" + name)
	if not s:
		return
	var p := _sfx[_next]
	_next = (_next + 1) % VOICES
	p.stream = s
	p.volume_db = db
	p.pitch_scale = pitch
	p.play()


## One-shot at a world position (falls off with distance, pans).
func play_at(parent: Node, name: String, pos: Vector2, db := 0.0, pitch := 1.0, dist := 260.0) -> void:
	var s := stream("sfx_" + name)
	if not s or not parent:
		return
	var p := AudioStreamPlayer2D.new()
	p.stream = s
	p.bus = "SFX"
	p.volume_db = db
	p.pitch_scale = pitch
	p.max_distance = dist
	p.attenuation = 1.6
	p.position = pos
	parent.add_child(p)
	p.play()
	p.finished.connect(p.queue_free)


## Positional loop (machines, drips, hum). Returns the player so the caller can free it.
func loop_at(parent: Node, name: String, pos: Vector2, db := 0.0, dist := 160.0) -> AudioStreamPlayer2D:
	var p := AudioStreamPlayer2D.new()
	p.stream = stream("loop_" + name, true)
	p.bus = "Ambience"
	p.volume_db = db
	p.max_distance = dist
	p.attenuation = 1.4
	p.position = pos
	parent.add_child(p)
	if p.stream:
		p.play(randf() * p.stream.get_length())
	return p


func ambience(name: String) -> void:
	_swap(_amb, "amb_" + name if name != "" else "", -6.0)


func music(name: String) -> void:
	_swap(_mus, "mus_" + name if name != "" else "", -8.0)


func _swap(p: AudioStreamPlayer, name: String, db: float) -> void:
	var s: AudioStreamWAV = stream(name, true) if name != "" else null
	if s and p.stream == s and p.playing:
		return
	var tw := create_tween()
	if p.playing:
		tw.tween_property(p, "volume_db", -40.0, 0.6)
	tw.tween_callback(func() -> void:
		if not s:
			p.stop()
			return
		p.stream = s
		p.volume_db = -40.0
		p.play())
	if s:
		tw.tween_property(p, "volume_db", db, 1.2)
