from common import L

# type: key | weapon | consumable | tool | scp | doc      use: heal | battery | sanity | full | read | event
ITEMS = {
    # ---------------------------------------------------------------- access
    "card_1": dict(type="key", icon="card_1", name=L("Keycard L1", "Tarjeta N1"),
                   desc=L("Level 1 access. Janitorial, cafeteria, offices.", "Acceso nivel 1. Limpieza, cafetería, oficinas.")),
    "card_2": dict(type="key", icon="card_2", name=L("Keycard L2", "Tarjeta N2"),
                   desc=L("Level 2 access. Light containment labs.", "Acceso nivel 2. Laboratorios de contención ligera.")),
    "card_3": dict(type="key", icon="card_3", name=L("Keycard L3", "Tarjeta N3"),
                   desc=L("Level 3 access. Medical wing, maintenance control.", "Acceso nivel 3. Ala médica, control de mantenimiento.")),
    "card_4": dict(type="key", icon="card_4", name=L("Keycard L4", "Tarjeta N4"),
                   desc=L("Level 4 access. Heavy containment.", "Acceso nivel 4. Contención pesada.")),
    "card_5": dict(type="key", icon="card_5", name=L("Keycard L5", "Tarjeta N5"),
                   desc=L("Level 5 access. Site command, the 079 core.", "Acceso nivel 5. Mando del sitio, núcleo de 079.")),
    "card_omni": dict(type="key", icon="card_omni", name=L("O5 Keycard", "Tarjeta O5"),
                      desc=L("A forged Overseer credential. Every door answers to it.", "Una credencial de Supervisor falsificada. Todas las puertas le obedecen.")),
    "office_key": dict(type="key", icon="key", name=L("Office key 2-B", "Llave de la oficina 2-B"),
                       desc=L("A brass key with a paper tag: 'E. VEGA'.", "Una llave de latón con una etiqueta de papel: 'E. VEGA'.")),
    "janitor_keys": dict(type="key", icon="key", name=L("Tomás' key ring", "Llavero de Tomás"),
                         desc=L("Heavy. Every maintenance hatch on Level -3.", "Pesado. Todas las escotillas de mantenimiento del Nivel -3.")),
    "fuse": dict(type="key", icon="fuse", name=L("Breaker fuse", "Fusible"),
                 desc=L("A 400 A cartridge fuse for the substation.", "Un fusible de cartucho de 400 A para la subestación.")),
    # ------------------------------------------------------------- weapons
    "pistol": dict(type="weapon", icon="pistol", name=L("Service pistol", "Pistola reglamentaria"),
                   desc=L("9 mm. Useless against most of what is loose in here.", "9 mm. Inútil contra casi todo lo que anda suelto aquí.")),
    "ammo": dict(type="weapon", icon="ammo", name=L("9 mm rounds", "Balas 9 mm"),
                 desc=L("Loose rounds. Count them.", "Balas sueltas. Cuéntalas.")),
    "baton": dict(type="weapon", icon="baton", name=L("Telescopic baton", "Porra extensible"),
                  desc=L("Better than bare hands.", "Mejor que las manos desnudas.")),
    "vest": dict(type="tool", icon="vest", name=L("Nine-Tailed Fox vest", "Chaleco de Nueve Colas"),
                 desc=L("Ceramic plates. Takes the edge off anything with claws.", "Placas cerámicas. Suaviza cualquier cosa con garras.")),
    # --------------------------------------------------------- consumables
    "medkit": dict(type="consumable", icon="medkit", use="heal", amount=45, name=L("Medkit", "Botiquín"),
                   desc=L("Gauze, antiseptic, a suture kit. Restores 45 health.", "Gasas, antiséptico, sutura. Recupera 45 de salud.")),
    "bandage": dict(type="consumable", icon="bandage", use="heal", amount=18, name=L("Bandage", "Venda"),
                    desc=L("Stops the bleeding for now. Restores 18 health.", "Detiene la hemorragia por ahora. Recupera 18 de salud.")),
    "adrenaline": dict(type="consumable", icon="adrenaline", use="heal", amount=70, name=L("Adrenaline", "Adrenalina"),
                       desc=L("Military auto-injector. Restores 70 health.", "Autoinyector militar. Recupera 70 de salud.")),
    "scp500": dict(type="consumable", icon="scp500", use="full", name=L("SCP-500 pill", "Píldora SCP-500"),
                   desc=L("Panacea. One pill cures every disease within two hours. There were 47 left.",
                          "Panacea. Una píldora cura toda enfermedad en dos horas. Quedaban 47.")),
    "battery": dict(type="consumable", icon="battery", use="battery", name=L("Battery", "Pila"),
                    desc=L("Fresh cells for the flashlight.", "Pilas nuevas para la linterna.")),
    "coffee": dict(type="consumable", icon="coffee", use="sanity", amount=30, name=L("Coffee", "Café"),
                   desc=L("Hot, bitter, real. Steadies the nerves (+30 sanity).", "Caliente, amargo, real. Calma los nervios (+30 cordura).")),
    "candy": dict(type="consumable", icon="candy", use="sanity", amount=12, name=L("Candy", "Caramelo"),
                  desc=L("Sugar and a memory of the surface (+12 sanity). Someone else here loves these.",
                         "Azúcar y un recuerdo de la superficie (+12 cordura). Alguien más aquí los adora.")),
    "coin": dict(type="tool", icon="coin", name=L("Quarter", "Moneda"), desc=L("Fifty cents buys one cup from SCP-294.", "Dos monedas compran una taza de SCP-294.")),
    # ----------------------------------------------------------- key items
    "radio": dict(type="tool", icon="radio", name=L("Radio", "Radio"), desc=L("Channel 4. Command listens. Something else might too.", "Canal 4. Mando escucha. Quizá algo más también.")),
    "bag096": dict(type="scp", icon="bag096", name=L("Containment hood", "Capucha de contención"),
                   desc=L("Opaque canvas with a drawstring. Once, it calmed SCP-096.", "Lona opaca con cordón. Una vez calmó a SCP-096.")),
    "lavender": dict(type="scp", icon="lavender", name=L("Lavender", "Lavanda"),
                     desc=L("Fresh sprigs. The file says it calms SCP-049's outbursts.", "Ramitas frescas. El expediente dice que calma los arrebatos de SCP-049.")),
    "recorder": dict(type="scp", icon="recorder", name=L("Recall recording", "Grabación de llamada"),
                     desc=L("Reyes' tape of a recontainment procedure. You don't want to know what is on it.",
                            "La cinta de Reyes con un procedimiento de recontención. No quieres saber qué contiene.")),
    "hcl": dict(type="scp", icon="hcl", name=L("HCl injector", "Inyector de HCl"),
                desc=L("Concentrated hydrochloric acid. The only thing that keeps SCP-682 down.", "Ácido clorhídrico concentrado. Lo único que mantiene a SCP-682 en el suelo.")),
    "dogtag": dict(type="tool", icon="dogtag", name=L("Dog tag", "Placa de identificación"),
                   desc=L("Nine-Tailed Fox. Reyes wants them back.", "Nueve Colas. Reyes las quiere de vuelta.")),
    "tape": dict(type="tool", icon="tape", name=L("Cassette tape", "Cinta de casete"),
                 desc=L("Unlabelled. Play it on a terminal.", "Sin etiqueta. Reprodúcela en un terminal.")),
    "cheese": dict(type="tool", icon="candy", name=L("Cheese", "Queso"), desc=L("Cheddar from the cafeteria. Someone small would like it.", "Cheddar de la cafetería. A alguien pequeño le gustaría.")),
}
